# Generated by Django 4.2.4 on 2023-10-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_remainder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='remainder',
            name='country',
        ),
        migrations.RemoveField(
            model_name='remainder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='remainder',
            name='image',
        ),
        migrations.RemoveField(
            model_name='remainder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='remainder',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='remainder',
            name='role',
        ),
        migrations.RemoveField(
            model_name='remainder',
            name='state',
        ),
        migrations.AddField(
            model_name='remainder',
            name='username',
            field=models.CharField(default='default_username', max_length=200),
        ),
        migrations.AlterField(
            model_name='remainder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
