# Generated by Django 4.2.4 on 2023-10-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_remainder', '0002_remove_remainder_address_remove_remainder_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainder',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
